"""
Exception handling

User-defined exceptions
namely Custom exceptions

Base class(type)  is Exception

"""

class CustomError(Exception):
    pass


class Custom2Error(Exception):
    pass

#

raise Custom2Error("custom 2 error message !")

# raise CustomError









