"""
module : exception handling
creating Custom Exceptions and save as external python files

"""

import module_7_exception.errors as err


raise err.CustomError("An error occurred")
